apiVersion: v1
kind: Pod
metadata:
  name: test-%%
spec:
  containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /secret
          name: secret
        - mountPath: /config
          name: config
  volumes:
    - name: secret
      secret:
        secretName: secret-%%
    - name: config
      configMap:
        name: config-%%
---
apiVersion: v1
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
kind: Secret
metadata:
  name: secret-%%
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-%%
data:
  id: |
    index=%%
  states: |
    washington=olympia
    delaware=dover
  ice.cream: |
    strawberry=balsamic
    caramel=salted
